name: Sign Artifact
on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      subject-digest:
        required: true
        type: string
      oidc-provider:
        required: true
        type: string
      jfrog-platform-host:
        required: true
        type: string


jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    - name: Setup JFrog CLI
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://${{ jfrog-platform-host }}
      with:  
        version: latest
        oidc-provider-name: ${{ inputs.oidc-provider }}        
        
    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ${{ inputs.subject-name }}
        subject-digest: ${{ inputs.subject-digest }}
