name: JFrog Traceability

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  git-evidence:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/github-evidence@v1
        with:
          jf_url: ${{ vars.JF_URL }}
          oidc_provider_name: ${{ vars.OIDC_PROVIDER_NAME }}
          evidence_signing_key: ${{ secrets.EVIDENCE_SIGNING_KEY }}
          evidence_key_alias: ${{ vars.EVIDENCE_PUBLIC_KEY_ALIAS }}
